import { RadioStation, Alarm } from '../types/radio';

export const INITIAL_STATIONS: RadioStation[] = [
  {
    id: 'heart-80s',
    name: 'Heart 80s',
    country: 'United Kingdom',
    countryCode: 'GB',
    genre: '80s',
    tags: ['80s', 'national', 'pop', 'retro'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://media-ssl.musicradio.com/Heart80s',
    ip: '157.230.29.155',
    color: '#8B5CF6',
    accentColor: '#EF4444',
    currentArtist: 'Rick Astley',
    currentTrack: 'Never Gonna Give You Up',
    isLive: true,
    frequency: 'DAB 11D',
    description: 'Non-stop 80s feel good hits from the UK'
  },
  {
    id: 'cadena-ser',
    name: 'Cadena SER',
    country: 'Spain',
    countryCode: 'ES',
    genre: 'News',
    tags: ['news', 'talk', 'informativos', 'deportes'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3',
    ip: '194.224.110.12',
    color: '#F59E0B',
    accentColor: '#10B981',
    currentArtist: 'Cadena SER',
    currentTrack: 'Hoy por Hoy - Informativo Matinal',
    isLive: true,
    frequency: '105.4 FM',
    description: 'La emisora generalista líder de información en España'
  },
  {
    id: 'pure-ibiza-radio',
    name: 'Pure Ibiza Radio',
    country: 'Spain',
    countryCode: 'ES',
    genre: 'Electronic',
    tags: ['dance', 'electronic', 'deep house', 'ibiza'],
    bitrate: 64,
    format: 'AAC',
    streamUrl: 'https://pureibizaradio.com/stream',
    ip: '178.33.161.22',
    color: '#06B6D4',
    accentColor: '#3B82F6',
    currentArtist: 'Pete Tha Zouk',
    currentTrack: 'Sunset Sessions Live from Playa d’en Bossa',
    isLive: true,
    frequency: '97.2 FM',
    description: 'Pure Balearic sound, deep house & underground electronic beats'
  },
  {
    id: 'cadena-100',
    name: 'Cadena 100',
    country: 'Spain',
    countryCode: 'ES',
    genre: 'Pop',
    tags: ['pop', 'latin', 'hits', 'variety'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://cadena100-cope.flumotion.com/chunks.m3u8',
    ip: '195.55.74.80',
    color: '#F43F5E',
    accentColor: '#FFFFFF',
    currentArtist: 'Manuel Carrasco',
    currentTrack: 'Fue - Directo España',
    isLive: true,
    frequency: '99.5 FM',
    description: 'La mejor variedad musical y los números uno del pop'
  },
  {
    id: 'rock-fm',
    name: 'RockFM 101.7',
    country: 'Spain',
    countryCode: 'ES',
    genre: 'Rock',
    tags: ['rock', 'classic rock', 'guitar', 'legendary'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://rockfm-cope.flumotion.com/chunks.m3u8',
    ip: '212.89.2.14',
    color: '#3B82F6',
    accentColor: '#EF4444',
    currentArtist: 'Queen',
    currentTrack: 'Bohemian Rhapsody',
    isLive: true,
    frequency: '101.7 FM',
    description: '1 hora de rock sin pausa, los mejores clásicos del rock'
  },
  {
    id: 'cadena-dial',
    name: 'Cadena Dial',
    country: 'Spain',
    countryCode: 'ES',
    genre: 'Latin',
    tags: ['música en español', 'pop latino', 'baladas'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL.mp3',
    ip: '194.224.110.15',
    color: '#14B8A6',
    accentColor: '#10B981',
    currentArtist: 'Alejandro Sanz',
    currentTrack: 'Corazón Partío',
    isLive: true,
    frequency: '91.7 FM',
    description: 'Lo mejor de nuestra música en español'
  },
  {
    id: 'los40-spain',
    name: 'LOS40 España',
    country: 'Spain',
    countryCode: 'ES',
    genre: 'Pop',
    tags: ['top 40', 'pop', 'urban', 'hits'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40.mp3',
    ip: '194.224.110.18',
    color: '#F59E0B',
    accentColor: '#8B5CF6',
    currentArtist: 'Dua Lipa',
    currentTrack: 'Houdini',
    isLive: true,
    frequency: '93.9 FM',
    description: 'Todos los éxitos, novedades y la lista oficial LOS40'
  },
  {
    id: '80-exitos',
    name: '_80 EXITOS',
    country: 'Spain',
    countryCode: 'ES',
    genre: '80s',
    tags: ['70s', '80s', 'retro', 'nostalgia'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://stream.zeno.fm/f3wvbbqmdg8uv',
    ip: '159.65.120.44',
    color: '#84CC16',
    accentColor: '#334155',
    currentArtist: 'Michael Jackson',
    currentTrack: 'Billie Jean',
    isLive: true,
    frequency: 'Online HD',
    description: 'Los mayores números uno de las décadas doradas'
  },
  {
    id: 'somafm-groovesalad',
    name: 'SomaFM: Groove Salad',
    country: 'United States',
    countryCode: 'US',
    genre: 'Lo-Fi',
    tags: ['chillout', 'downtempo', 'ambient', 'lo-fi'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://ice1.somafm.com/groovesalad-128-mp3',
    ip: '205.188.215.228',
    color: '#10B981',
    accentColor: '#06B6D4',
    currentArtist: 'Tycho',
    currentTrack: 'A Walk (Downtempo Dub Mix)',
    isLive: true,
    frequency: 'San Francisco Web',
    description: 'A nicely chilled plate of ambient/downtempo beats and grooves'
  },
  {
    id: 'bbc-radio-1',
    name: 'BBC Radio 1',
    country: 'United Kingdom',
    countryCode: 'GB',
    genre: 'Pop',
    tags: ['pop', 'indie', 'dance', 'uk hits'],
    bitrate: 128,
    format: 'AAC',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
    ip: '212.58.244.70',
    color: '#EF4444',
    accentColor: '#FFFFFF',
    currentArtist: 'Charli xcx',
    currentTrack: '360 (Radio 1 Live Lounge)',
    isLive: true,
    frequency: '98.8 FM',
    description: 'The best new music, groundbreaking DJs and entertainment from London'
  },
  {
    id: 'jazz-24',
    name: 'Jazz24',
    country: 'United States',
    countryCode: 'US',
    genre: 'Jazz',
    tags: ['jazz', 'blues', 'bebop', 'smooth jazz'],
    bitrate: 128,
    format: 'MP3',
    streamUrl: 'https://live.wksu.org/jazz.mp3',
    ip: '198.27.70.42',
    color: '#D97706',
    accentColor: '#8B5CF6',
    currentArtist: 'Miles Davis',
    currentTrack: 'So What (Kind of Blue)',
    isLive: true,
    frequency: 'Seattle / Tacoma',
    description: 'Classic jazz masters alongside the greatest jazz talents of today'
  },
  {
    id: 'fip-paris',
    name: 'FIP Radio Paris',
    country: 'France',
    countryCode: 'FR',
    genre: 'Eclectic',
    tags: ['eclectic', 'world', 'jazz', 'rock', 'paris'],
    bitrate: 192,
    format: 'AAC',
    streamUrl: 'https://icecast.radiofrance.fr/fip-midfi.mp3',
    ip: '151.101.130.133',
    color: '#F43F5E',
    accentColor: '#F59E0B',
    currentArtist: 'Air',
    currentTrack: 'La Femme d’Argent',
    isLive: true,
    frequency: '105.1 FM',
    description: 'Radio éclectique sans interruption publicitaire de Radio France'
  },
  {
    id: 'techno-base-fm',
    name: 'TechnoBase.FM',
    country: 'Germany',
    countryCode: 'DE',
    genre: 'Techno',
    tags: ['techno', 'hands up', 'trance', 'electronic'],
    bitrate: 192,
    format: 'MP3',
    streamUrl: 'https://listen.technobase.fm/tunein-mp3-pls',
    ip: '176.31.240.11',
    color: '#8B5CF6',
    accentColor: '#06B6D4',
    currentArtist: 'Scooter',
    currentTrack: 'Hyper Hyper (2025 Rework)',
    isLive: true,
    frequency: 'Online 24/7',
    description: 'The number one club and hands-up internet radio station in Europe'
  },
  {
    id: 'tokyo-fm',
    name: 'Tokyo FM 80.0',
    country: 'Japan',
    countryCode: 'JP',
    genre: 'J-Pop',
    tags: ['j-pop', 'city pop', 'anime', 'japan'],
    bitrate: 128,
    format: 'AAC',
    streamUrl: 'https://stream.zeno.fm/54h8u5wvptzuv',
    ip: '203.141.135.2',
    color: '#F43F5E',
    accentColor: '#10B981',
    currentArtist: 'Yoasobi',
    currentTrack: 'Idol (Live Studio Mix)',
    isLive: true,
    frequency: '80.0 FM',
    description: 'Broadcasting from the heart of Tokyo with the latest J-pop & City Pop'
  }
];

export const INITIAL_ALARMS: Alarm[] = [
  {
    id: 'alarm-1',
    time: '07:30',
    days: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie'],
    stationId: 'cadena-ser',
    stationName: 'Cadena SER (Informativos)',
    active: true,
    label: 'Despertador Semana',
    volume: 85
  },
  {
    id: 'alarm-2',
    time: '09:00',
    days: ['Sáb', 'Dom'],
    stationId: 'los40-spain',
    stationName: 'LOS40 España',
    active: false,
    label: 'Fin de Semana Música',
    volume: 75
  }
];

export const INITIAL_FAVORITES: string[] = [
  'heart-80s',
  'pure-ibiza-radio',
  'cadena-100',
  'rock-fm',
  'cadena-dial',
  '80-exitos'
];

export const NEWS_TICKER_ITEMS = [
  'Seguridad en las fronteras españolas bajo revisión constante',
  'Actualidad nacional: las noticias más destacadas de este miércoles',
  'Un vecino de Granada relata el pánico vivido durante el terremoto',
  'La Agencia Estatal de Meteorología prevé temperaturas estables para el litoral mediterráneo',
  'Nuevo récord de audiencia en emisiones de radio digital DAB+ y streaming de alta definición',
  'Innovación tecnológica: despliegue de redes 5G+ optimiza la latencia de streams sonoros a menos de 40ms'
];

export const GENRES_LIST = [
  { id: '80s', name: '80s & Retro', count: 18, color: '#8B5CF6', icon: 'radio' },
  { id: 'news', name: 'Noticias & Talk', count: 24, color: '#EF4444', icon: 'newspaper' },
  { id: 'pop', name: 'Pop & Top 40', count: 42, color: '#F43F5E', icon: 'music_note' },
  { id: 'rock', name: 'Rock Clásico', count: 31, color: '#3B82F6', icon: 'electric_bolt' },
  { id: 'electronic', name: 'Electronic & Dance', count: 38, color: '#06B6D4', icon: 'headphones' },
  { id: 'jazz', name: 'Jazz & Blues', count: 19, color: '#D97706', icon: 'piano' },
  { id: 'lo-fi', name: 'Lo-Fi & Ambient', count: 22, color: '#10B981', icon: 'spa' },
  { id: 'latin', name: 'Latino & Español', count: 29, color: '#14B8A6', icon: 'celebration' },
  { id: 'techno', name: 'Techno & Club', count: 27, color: '#84CC16', icon: 'graphic_eq' }
];

export const COUNTRIES_LIST = [
  { code: 'ES', name: 'España', count: 48, flag: '🇪🇸', activeColor: '#F59E0B' },
  { code: 'GB', name: 'United Kingdom', count: 36, flag: '🇬🇧', activeColor: '#3B82F6' },
  { code: 'US', name: 'United States', count: 64, flag: '🇺🇸', activeColor: '#EF4444' },
  { code: 'FR', name: 'France', count: 28, flag: '🇫🇷', activeColor: '#06B6D4' },
  { code: 'DE', name: 'Germany', count: 32, flag: '🇩🇪', activeColor: '#84CC16' },
  { code: 'JP', name: 'Japan', count: 21, flag: '🇯🇵', activeColor: '#F43F5E' },
  { code: 'MX', name: 'México', count: 19, flag: '🇲🇽', activeColor: '#10B981' },
  { code: 'IT', name: 'Italia', count: 22, flag: '🇮🇹', activeColor: '#8B5CF6' },
  { code: 'AR', name: 'Argentina', count: 17, flag: '🇦🇷', activeColor: '#3B82F6' },
  { code: 'CO', name: 'Colombia', count: 14, flag: '🇨🇴', activeColor: '#F59E0B' }
];
